### ISSUE TITLE
FaucetUntaggedRestBcastIPv6RouteTest fails on virtual hardware testbed

### ISSUE THREAD

**Issue by gizmoguy** [faucetsdn/faucet#3279] opened 2019-10-07 01:57 UTC
```
======================================================================
FAIL: test_untagged (mininet_tests.FaucetUntaggedRestBcastIPv6RouteTest)
----------------------------------------------------------------------

Traceback (most recent call last):
  File "/faucet-src/tests/integration/mininet_tests.py", line 6521, in test_untagged
    self.verify_ipv6_routing_mesh()
  File "/faucet-src/clib/mininet_test_base.py", line 2722, in verify_ipv6_routing_mesh
    second_host, second_host_ip, second_host_routed_ip)
  File "/faucet-src/clib/mininet_test_base.py", line 2702, in verify_ipv6_routing_pair
    second_host, second_host_ip, second_host_routed_ip)
  File "/faucet-src/clib/mininet_test_base.py", line 2670, in verify_ipv6_routing
    first_host.MAC(), first_host_routed_ip.network)
  File "/faucet-src/clib/mininet_test_base.py", line 2488, in wait_for_route_as_flow
    actions=[nexthop_action], ofa_match=False)
  File "/faucet-src/clib/mininet_test_base.py", line 1039, in wait_until_matching_flow
    msg=('match: %s table_id: %u actions: %s' % (match, table_id, actions)))
AssertionError: [] is not true : match: {'ipv6_dst': 'fc00::10:0/ffff:ffff:ffff:ffff:ffff:ffff:ffff:0', 'dl_type': 34525} table_id: 2 actions: ['SET_FIELD: {eth_dst:42:71:9b:f0:ed:82}']
```

**Comment by anarkiwi** [comment] 2019-10-25 18:10
Seems to be OK here. Still attempting to reproduce.

faucet@faucet:~/faucet$ ../bin/runsimhw.sh -nik FaucetUntaggedRestBcastIPv6RouteTest
Sending build context to Docker daemon  57.69MB
Step 1/4 : FROM faucet/test-base:6.0.0
6.0.0: Pulling from faucet/test-base
Digest: sha256:514d4538bbcf8e00f72f9c33ba7c595c48983456d72f3bdce27f4721c18b38a1
Status: Image is up to date for faucet/test-base:6.0.0
 ---> 6020529886b7
Step 2/4 : COPY ./ /faucet-src/
 ---> 97a2db9e2ece
Step 3/4 : WORKDIR /faucet-src/
 ---> Running in 574eb6fe1407
Removing intermediate container 574eb6fe1407
 ---> 371afc79f11b
Step 4/4 : CMD ["docker/runtests.sh"]
 ---> Running in 3a710e1a1d10
Removing intermediate container 3a710e1a1d10
 ---> 97217e2ee964
Successfully built 97217e2ee964
Successfully tagged faucet/tests:latest
Using pip cache
pip3 install -q --upgrade --cache-dir=/var/tmp/pip-cache -r /faucet-src/test-requirements.txt has exit status 0
pip3 install -q --upgrade --cache-dir=/var/tmp/pip-cache -r /faucet-src/fuzz-requirements.txt has exit status 0
pip3 install -q --upgrade --cache-dir=/var/tmp/pip-cache -r /faucet-src/docs/requirements.txt has exit status 0
pip3 install -q --upgrade --cache-dir=/var/tmp/pip-cache -r /faucet-src/adapters/vendors/rabbitmq/requirements.txt has exit status 0
========== checking IPv4/v6 localhost is up =====
PING ::1(::1) 56 data bytes
64 bytes from ::1: icmp_seq=1 ttl=64 time=0.020 ms

--- ::1 ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 0.020/0.020/0.020/0.000 ms
PING 127.0.0.1 (127.0.0.1) 56(84) bytes of data.
64 bytes from 127.0.0.1: icmp_seq=1 ttl=64 time=0.015 ms

--- 127.0.0.1 ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 0.015/0.015/0.015/0.000 ms
========== Starting OVS =========================
 * /usr/local/etc/openvswitch/conf.db does not exist
 * Creating empty database /usr/local/etc/openvswitch/conf.db
 * Starting ovsdb-server
 * system ID not configured, please use --system-id
 * Configuring Open vSwitch system IDs
 * Starting ovs-vswitchd
 * Enabling remote OVSDB managers
5c136bcf-dd0a-4c4b-b32e-7e098e5dc864
    ovs_version: "2.12.0"
sysctl: cannot stat /proc/sys/net/ipv4/neigh/default/gc_interval: No such file or directory
sysctl: cannot stat /proc/sys/net/ipv4/neigh/default/gc_thresh1: No such file or directory
sysctl: cannot stat /proc/sys/net/ipv4/neigh/default/gc_thresh2: No such file or directory
sysctl: cannot stat /proc/sys/net/ipv4/neigh/default/gc_thresh3: No such file or directory
sysctl: cannot stat /proc/sys/net/ipv6/neigh/default/gc_interval: No such file or directory
sysctl: cannot stat /proc/sys/net/ipv6/neigh/default/gc_thresh1: No such file or directory
sysctl: cannot stat /proc/sys/net/ipv6/neigh/default/gc_thresh2: No such file or directory
sysctl: cannot stat /proc/sys/net/ipv6/neigh/default/gc_thresh3: No such file or directory
Generating locales (this might take a while)...
  en_US.UTF-8... done
Generation complete.
========== Starting docker container ==========
 * Starting Docker: docker                                                                                  [ OK ] 
========== Running faucet system tests ==========
testing module mininet_tests
Cleaning up test interfaces, processes and openvswitch configuration from previous test runs
========== Simulating hardware test switch ==========
hw_switch: True
hardware: 'Open vSwitch TFM'
of_port: 6653
gauge_of_port: 6654
cpn_intf: lo
dp_ports:
  5: hwp5
  4: hwp4
  3: hwp3
  2: hwp2

dpid: 0x0000aeab3e0db243
5c136bcf-dd0a-4c4b-b32e-7e098e5dc864
    Bridge hwbr
        Controller "tcp:127.0.0.1:6654"
        Controller "tcp:127.0.0.1:6653"
        fail_mode: secure
        Port "phwp2"
            Interface "phwp2"
        Port "phwp4"
            Interface "phwp4"
        Port "phwp5"
            Interface "phwp5"
        Port "phwp3"
            Interface "phwp3"
        Port hwbr
            Interface hwbr
                type: internal
    ovs_version: "2.12.0"
OFPST_PORT reply (xid=0x2): 5 ports
  port  phwp4: rx pkts=0, bytes=0, drop=0, errs=0, frame=0, over=0, crc=0
           tx pkts=0, bytes=0, drop=0, errs=0, coll=0
  port LOCAL: rx pkts=0, bytes=0, drop=0, errs=0, frame=0, over=0, crc=0
           tx pkts=0, bytes=0, drop=0, errs=0, coll=0
  port  phwp5: rx pkts=0, bytes=0, drop=0, errs=0, frame=0, over=0, crc=0
           tx pkts=0, bytes=0, drop=0, errs=0, coll=0
  port  phwp2: rx pkts=0, bytes=0, drop=0, errs=0, frame=0, over=0, crc=0
           tx pkts=0, bytes=0, drop=0, errs=0, coll=0
  port  phwp3: rx pkts=0, bytes=0, drop=0, errs=0, frame=0, over=0, crc=0
           tx pkts=0, bytes=0, drop=0, errs=0, coll=0
testing module mininet_tests
Skipping dependency checks
port order: -o 3,2,1,0
Using config from /etc/faucet/hw_switch_config.yaml
Testing hardware, forcing test serialization
Logging test results in /var/tmp/faucet-tests-_3smk88y
test ports server started
adding test FaucetUntaggedRestBcastIPv6RouteTest

----------------------------------------------------------------------
Ran 0 tests in 0.000s

OK
running 0 tests in parallel and 1 tests serial
test_untagged (mininet_tests.FaucetUntaggedRestBcastIPv6RouteTest) ... *** Error setting resource limits. Mininet's performance may be affected.
FaucetUntaggedRestBcastIPv6RouteTest-test_untagged: 15620 mbps to fc00::20:1
FaucetUntaggedRestBcastIPv6RouteTest-test_untagged: 15617 mbps to fc00::10:1
FaucetUntaggedRestBcastIPv6RouteTest-test_untagged: 15624 mbps to fc00::30:1
FaucetUntaggedRestBcastIPv6RouteTest-test_untagged: 15595 mbps to fc00::10:1
FaucetUntaggedRestBcastIPv6RouteTest-test_untagged: 15628 mbps to fc00::20:1
FaucetUntaggedRestBcastIPv6RouteTest-test_untagged: 15616 mbps to fc00::10:1
FaucetUntaggedRestBcastIPv6RouteTest-test_untagged: 15610 mbps to fc00::30:1
FaucetUntaggedRestBcastIPv6RouteTest-test_untagged: 15627 mbps to fc00::10:1
FaucetUntaggedRestBcastIPv6RouteTest-test_untagged: 15617 mbps to fc00::20:1
FaucetUntaggedRestBcastIPv6RouteTest-test_untagged: 15603 mbps to fc00::10:1
FaucetUntaggedRestBcastIPv6RouteTest-test_untagged: 15609 mbps to fc00::30:1
FaucetUntaggedRestBcastIPv6RouteTest-test_untagged: 15635 mbps to fc00::10:1
FaucetUntaggedRestBcastIPv6RouteTest-test_untagged: 15623 mbps to fc00::20:1
FaucetUntaggedRestBcastIPv6RouteTest-test_untagged: 15603 mbps to fc00::10:1
FaucetUntaggedRestBcastIPv6RouteTest-test_untagged: 15610 mbps to fc00::30:1
FaucetUntaggedRestBcastIPv6RouteTest-test_untagged: 15587 mbps to fc00::10:1
ok

----------------------------------------------------------------------
Ran 1 test in 158.814s

OK

**Comment by anarkiwi** [comment] 2019-10-26 02:04
Fixed in https://github.com/faucetsdn/faucet/pull/3303

**Closed by anarkiwi** 2019-10-26 02:04 UTC
Labels: bug
