### ISSUE TITLE
Faucet event socket is enabled by default

### ISSUE THREAD

**Issue by byllyfish** [faucetsdn/faucet#1416] opened 2017-12-14 02:53 UTC
I thought the intention of the Faucet event socket was to be turned off by default, so it could be enabled when needed.

FAUCET_EVENT_SOCK currently defaults to '0'. It's a semi-boolean setting, but the code maps '0' to '/var/run/faucet/faucet.sock' which enables it.

**Comment by cglewis** [comment] 2017-12-14 03:02
@byllyfish yeah, it is supposed to be turned off by default.  I think this can be resolved with:

```
diff --git a/faucet/faucet_experimental_event.py b/faucet/faucet_experimental_event.py
index 26aeb660..ff9dc0f4 100644
--- a/faucet/faucet_experimental_event.py
+++ b/faucet/faucet_experimental_event.py
@@ -39,7 +39,7 @@ class FaucetExperimentalEventNotifier(object):
     """Event notification, via Unix domain socket."""
 
     def __init__(self, socket_path, metrics, logger):
-        if socket_path:
+        if socket_path and socket_path != '0':
             if os.path.exists(os.path.dirname(socket_path)):
                 self.socket_path = socket_path
             else:
```

**Comment by byllyfish** [comment] 2017-12-14 03:09
Okay, I wanted to make sure.

A cleaner solution is to move the logic of setting the default truthy value
('/var/run/faucet/faucet.sock') into get_setting() in valve_util.py so the
path can be adjusted for virtualenv.

**Comment by gizmoguy** [comment] 2017-12-14 04:09
Ultimately this was the cause of #1388. I've added code that roughly disables the event subsystem if it can't write to /var/run/faucet/faucet.sock, but yes if you're running as root the event subsystem will always be enabled.

Happy to take PRs to fix, either way sounds ok. Being virtualenv compliant is a nice thing to have though.

**Comment by byllyfish** [comment] 2017-12-15 02:55
I am getting a PR ready for this one.

**Closed** 2017-12-19 03:01 UTC
Labels: bug
