### ISSUE TITLE
Faucet hangs after some reconfiguration attempts.

### ISSUE THREAD

**Issue by grafnu** [faucetsdn/faucet#2844] opened 2019-03-10 17:02 UTC
My integration tests are turning up an intermittent case where Faucet just hangs (not crash, but does not continue to function).  I've traced it down to a situation where there's an error in the RYU logs that causes the data-path to disconnect, but Faucet does not re-connect.  This is related to issue #2843, but different because in that case the error is not fatal, while this is a secondary condition that actually breaks the system.

The problem is exhibited in the [Faucet logs with a "datapath down" message](https://travis-ci.org/grafnu/daq/jobs/504000121#L6393), and it never comes back (and so future flow mods fail). You can see [the same event in the RYU logs](https://travis-ci.org/grafnu/daq/jobs/504000121#L5405). This is  [different than other working situations](https://travis-ci.org/grafnu/daq/jobs/504000121#L7432) where Faucet reconnects after the problem.  (I just checked and unfortunately travis links seem to be broken, and so the links don't jump to the right line as indicated in the URL requiring some manually scrolling.)

Restarting Faucet with no other changes fixes the problem.  It's  hard to nail down the problem further because it's intermittent and in the middle of an integration test, so hard to pinpoint down a specific triggering problem.

**Comment by anarkiwi** [comment] 2019-03-10 22:12
The DP disconnecting is normal. This is because, if we detect a situation where we have to cold start after a big config change, we need the DP to disconnect and come back so we have a chance to learn about new ports and their op status.

The exceptions you're seeing with config diffs naturally are not normal - per comments on the other bug, please provide the "killer" configs so we can reproduce the problem - the logs unfortunately are not sufficient).

**Comment by grafnu** [comment] 2019-03-11 04:55
Here's two configs where alternating between them triggers the sequence error problem.  It doesn't (always?) cause Faucet to choke, so it might not be the root cause still -- but it would be good to know that there's nothing else going on.  I'll try out the new patch (as per the other bug) and see if anything changes in terms of useful info.

[faucet_two.txt](https://github.com/faucetsdn/faucet/files/2950688/faucet_two.txt)
[faucet_one.txt](https://github.com/faucetsdn/faucet/files/2950689/faucet_one.txt)

**Comment by anarkiwi** [comment] 2019-03-11 21:58
Unfortunately these configs don't seem to cause any problems here - looks like we need to narrow down further to the real culprit. In the meantime, today's release contains a workaround for the datadiff exception.

**Comment by grafnu** [comment] 2019-03-12 04:53
I think there's a race condition when a configuration triggers a cold start, and then a new configuration arrives before the DPs have reconnected. I tested this by adding a sleep statement in my code after I change configurations, to prevent a new one from coming in too quickly -- and the problem has cleared up.

Obviously not the right fix, but I think it confirms the problem. I'm not quite sure what the proper fix is, but likely when the DPs are disconnected they need to be marked as such so any new incoming config change is handled more like system startup (before any DPs have connected).

**Comment by cglewis** [comment] 2019-03-12 04:57
Oh interesting, I’ve actually been experiencing a similar problem that I assumed was mininet’s fault, but it is always on a reconfiguration with a cold start and DPs connecting/disconnecting, so maybe it’s the same issue. I haven’t come up with a clean reproducible test yet though as I assumed the problem was out of scope for Faucet.

**Comment by anarkiwi** [comment] 2019-03-13 04:51
OK... DPs are always marked as down when they're down (whatever the cause) and you'll get a cold start. So I'm not sure that's the cause. Can you expand a bit on how new configs are arriving? Are you sending a HUP, or using the stat based reload mechanism? If HUP I can investigate whether it makes a difference if you HUP while the last HUP is still being processed, but if you're using the stat based reloader then that doesn't explain it (because we're essentially co-operatively multitasking, the task that checks stat won't run until the new config is processed).

Can you remove the sleep please and check that the NotSequence exception is not happening anymore? I'd like to go back and eliminate a parser crash first before moving onto other possibilities.

**Comment by grafnu** [comment] 2019-03-13 05:21
NotSequence error still happening, with or without the sleep. 

I'm using the stat-based reload mechanism.

Is it possible that the ryu layer thinks the DP is down ([as per valve.py](https://github.com/faucetsdn/faucet/blob/master/faucet/valve.py#L1566)), but the faucet layer still thinks the DP is still there and then tries to send the (second update) config which then [just gets dropped with a log message](https://github.com/faucetsdn/faucet/blob/master/faucet/faucet.py#L170) but no programmatic impact? I do [see that error message in the logs](https://travis-ci.org/grafnu/daq/jobs/504965653#L6602) ("DP not up"), and then after that it seems like it never gets the memo that the DP has reconnected. Not exactly sure how the code works, but just pointing out some possibilities.

**Comment by cglewis** [comment] 2019-03-13 14:40
I'm also exclusively using the stat reload.

**Comment by anarkiwi** [comment] 2019-03-14 02:19
OK good stat based reload, that eliminates one set of possibilities around signal handling.

I'm puzzled how you can see the NotSequence error because the latest released code catches that. Can you cite the error again please, perhaps it's being raised somewhere else.

If there's an uncaught exception then that will cause all kinds of things to get stuck, so I don't think we can yet speculate on other causes until we've got to the bottom of where this exception is coming from.

**Comment by grafnu** [comment] 2019-03-14 03:02
Here's the exception -- this is from the "docker logs" using the -v option to faucet (and therefore ryu) to enable verbose logging.

```
EVENT Faucet->Faucet EventReconfigure
EVENT ofp_event->dpset EventOFPStateChange
tried SequenceMatcher but got error
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/datadiff/__init__.py", line 202, in try_diff_seq
    return diff_seq(a, b, context, depth, fromfile=fromfile, tofile=tofile)
  File "/usr/lib/python3.6/site-packages/datadiff/__init__.py", line 211, in diff_seq
    raise NotSequence("Not a sequence %s" % type(a))
datadiff.NotSequence: Not a sequence <class 'faucet.dp.DP'>
tried SequenceMatcher but got error
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/datadiff/__init__.py", line 202, in try_diff_seq
    return diff_seq(a, b, context, depth, fromfile=fromfile, tofile=tofile)
  File "/usr/lib/python3.6/site-packages/datadiff/__init__.py", line 211, in diff_seq
    raise NotSequence("Not a sequence %s" % type(a))
datadiff.NotSequence: Not a sequence <class 'faucet.port.Port'>
DPSET: unregister datapath <ryu.controller.controller.Datapath object at 0x7f6fdebb13c8>
EVENT dpset->Faucet EventDP
```

**Comment by anarkiwi** [comment] 2019-03-22 07:12
I can't comprehend how that exception can sneak past the catch for it. 

https://github.com/faucetsdn/faucet/pull/2879

I elected to entirely remove datadiff which appears to be unmaintained, and moved to difflib which is mainstream. Please try that PR as a patch.

**Comment by grafnu** [comment] 2019-03-22 16:08
Confirmed that this fixes the PR fixes the exception issue, but the root
problem with Faucet wedging are still there.

**Comment by anarkiwi** [comment] 2019-03-24 01:33
OK thank you that eliminates it as a potential cause.

I'll continue to investigate but in the meantime the more specific you can be (eg. a precise reproduction scenario) would be helpful.

**Comment by anarkiwi** [comment] 2019-03-24 08:18
Would you try https://github.com/faucetsdn/faucet/pull/2881, please?

**Comment by grafnu** [comment] 2019-03-24 19:12
Trying it out -- will let you know after I have some analysis (takes a few
runs sometimes to trigger)...

**Comment by anarkiwi** [comment] 2019-03-25 19:52
Has it made a difference? We have a release scheduled for today which it would be good to include this for if it resolves this problem for you (and the release will have fixes those other config diff exceptions and an exception catcher for dead threads).

**Comment by grafnu** [comment] 2019-03-25 20:11
Just checked, and it seems like it's dropped the failure rate of my test
from ~50% to ~10%, so I'm guessing there's a different issue floating
around with a similar effect. But, short of it is that this has
definitely improved things.

**Comment by anarkiwi** [comment] 2019-03-25 20:39
Excellent, thank you for the follow up, this problem has been causing me some sleepless nights.

Please keep us updated on your findings so whatever the cause is we can get it to 0% failure.

**Comment by grafnu** [comment] 2019-03-26 23:23
Ok -- have seen the problem again in the logs (with new version applied), included below is the difference for good vs. bad case. Here's the [complete log for both runs](https://github.com/faucetsdn/faucet/files/3010859/failure_log.txt) -- and you can find the specific spots by searching for the timestamp.  The ones below are the filtered filtered just for the specific DPIS 0x1. I'm trying to think what additional logging might be useful (e.g. maybe a tcpdump of the OF<->Faucet connection) -- I will try to capture more info, but this is just to capture what I've seen so far.

Working as intended:
```
Mar 26 17:32:51 faucet.valve INFO     DPID 1 (0x1) pri forcing DP reconnection to ensure ports are synchronized
Mar 26 17:32:51 faucet.valve INFO     DPID 1 (0x1) pri cold starting
Mar 26 17:32:51 faucet.valve WARNING  DPID 1 (0x1) pri datapath down
Mar 26 17:32:51 faucet.valve WARNING  DPID 1 (0x1) pri datapath down
Mar 26 17:32:51 faucet.valve INFO     DPID 1 (0x1) pri Cold start configuring DP
Mar 26 17:32:51 faucet.valve INFO     DPID 1 (0x1) pri Port 1 (stack_pri) configured
Mar 26 17:32:51 faucet.valve INFO     DPID 1 (0x1) pri Port 1002 (mirror-2) configured
```

I think the smoking gun here is that there never is a "Cold start configuring DP" message, which I think is caused by OF connecting back into Faucet after the disconnect.  Not working as intended (never recovers):
```
Mar 26 17:19:35 faucet.valve INFO     DPID 1 (0x1) pri all ports changed
Mar 26 17:19:35 faucet.valve INFO     DPID 1 (0x1) pri forcing DP reconnection to ensure ports are synchronized
Mar 26 17:19:35 faucet.valve INFO     DPID 1 (0x1) pri cold starting
Mar 26 17:19:35 faucet.valve WARNING  DPID 1 (0x1) pri datapath down
Mar 26 17:19:35 faucet.valve WARNING  DPID 1 (0x1) pri datapath down
Mar 26 17:20:08 faucet.valve INFO     DPID 1 (0x1) pri ACL dp_pri_incoming_acl changed:   {
Mar 26 17:20:08 faucet.valve INFO     DPID 1 (0x1) pri ACL dp_pri_portset_2_acl changed:   {
Mar 26 17:20:08 faucet.valve INFO     DPID 1 (0x1) pri ACL dp_sec_port_1_acl changed:   {
Mar 26 17:20:08 faucet.valve INFO     DPID 1 (0x1) pri no VLAN config changes
```

**Comment by grafnu** [comment] 2019-04-01 20:32
Current theory is that this is an OVS issue where OVS hangs when a connection is closed. I see Faucet closing the connection, but then there's nothing in the OVS logs indicating such. This is a very sporadic issue, as well. So, before doing much more with this I'd want to distill it down to a more succinct test case and then see exactly what's going on.  This is not currently blocking anything since it's only shown up in CI testing on Travis, not real systems.

**Comment by cglewis** [comment] 2019-04-01 20:37
@grafnu that is consistent with the behavior I occasionally see as well, but I haven't come up with an easily reproducible test.

**Comment by anarkiwi** [comment] 2019-04-30 21:00
Please re-open if any detail/suggesting FAUCET is a cause and we will investigate. You may be seeing an OVS vswitchd crash (have observed this occasionally).

Try running your tests with:

ulimit -c unlimited
echo '/var/tmp/core.%h.%e.%t' > /proc/sys/kernel/core_pattern

And then:

 --privileged 
    --ulimit core=99999999999:99999999999 

As args to --docker run.

**Closed by anarkiwi** 2019-04-30 21:00 UTC
Labels: bug
