### ISSUE TITLE
Learning after stack topology change only works with broadcast not unicast

### ISSUE THREAD

**Issue by gizmoguy** [faucetsdn/faucet#3251] opened 2019-09-23 02:43 UTC
After a stack topology change we might see lots of spurious flooded unicast traffic, which we suspect is caused by a bug that causes learning from unicast to fail until we see some broadcast traffic from the host:

```
Sep 23 01:53:17 faucet.valve INFO     DPID 115621677691 (0x1aeb96ca7b) t1-sw2 L2 learned a0:36:9f:01:de:1d (L2 type 0x0800, L2 dst a0:36:9f:01:de:1c, L3 src 10.0.0.2, L3 dst 10.0.0.1) Port 6 VLAN 31 (1 hosts total) from remote DP t2-sw1 port Port 7
Sep 23 01:53:18 faucet.valve INFO     DPID 115621677691 (0x1aeb96ca7b) t1-sw2 L2 learned a0:36:9f:01:de:1d (L2 type 0x0800, L2 dst a0:36:9f:01:de:1c, L3 src 10.0.0.2, L3 dst 10.0.0.1) Port 6 VLAN 31 (1 hosts total) from remote DP t2-sw1 port Port 7
Sep 23 01:53:19 faucet.valve INFO     DPID 115621677691 (0x1aeb96ca7b) t1-sw2 L2 learned a0:36:9f:01:de:1d (L2 type 0x0800, L2 dst a0:36:9f:01:de:1c, L3 src 10.0.0.2, L3 dst 10.0.0.1) Port 6 VLAN 31 (1 hosts total) from remote DP t2-sw1 port Port 7
Sep 23 01:53:20 faucet.valve INFO     DPID 115621677691 (0x1aeb96ca7b) t1-sw2 L2 learned a0:36:9f:01:de:1d (L2 type 0x0800, L2 dst a0:36:9f:01:de:1c, L3 src 10.0.0.2, L3 dst 10.0.0.1) Port 6 VLAN 31 (1 hosts total) from remote DP t2-sw1 port Port 7
Sep 23 01:53:21 faucet.valve INFO     DPID 115621677691 (0x1aeb96ca7b) t1-sw2 L2 learned a0:36:9f:01:de:1d (L2 type 0x0800, L2 dst a0:36:9f:01:de:1c, L3 src 10.0.0.2, L3 dst 10.0.0.1) Port 6 VLAN 31 (1 hosts total) from remote DP t2-sw1 port Port 7
Sep 23 01:53:22 faucet.valve INFO     DPID 115621677691 (0x1aeb96ca7b) t1-sw2 L2 learned a0:36:9f:01:de:1d (L2 type 0x0800, L2 dst a0:36:9f:01:de:1c, L3 src 10.0.0.2, L3 dst 10.0.0.1) Port 6 VLAN 31 (1 hosts total) from remote DP t2-sw1 port Port 7
Sep 23 01:53:23 faucet.valve INFO     DPID 115621677691 (0x1aeb96ca7b) t1-sw2 L2 learned a0:36:9f:01:de:1d (L2 type 0x0800, L2 dst a0:36:9f:01:de:1c, L3 src 10.0.0.2, L3 dst 10.0.0.1) Port 6 VLAN 31 (1 hosts total) from remote DP t2-sw1 port Port 7
Sep 23 01:53:24 faucet.valve INFO     DPID 115621677691 (0x1aeb96ca7b) t1-sw2 L2 learned a0:36:9f:01:de:1d (L2 type 0x0800, L2 dst a0:36:9f:01:de:1c, L3 src 10.0.0.2, L3 dst 10.0.0.1) Port 6 VLAN 31 (1 hosts total) from remote DP t2-sw1 port Port 7
Sep 23 01:53:25 faucet.valve INFO     DPID 115621677691 (0x1aeb96ca7b) t1-sw2 L2 learned a0:36:9f:01:de:1d (L2 type 0x0800, L2 dst a0:36:9f:01:de:1c, L3 src 10.0.0.2, L3 dst 10.0.0.1) Port 6 VLAN 31 (1 hosts total) from remote DP t2-sw1 port Port 7
Sep 23 01:53:26 faucet.valve INFO     DPID 115621677691 (0x1aeb96ca7b) t1-sw2 L2 learned a0:36:9f:01:de:1d (L2 type 0x0800, L2 dst a0:36:9f:01:de:1c, L3 src 10.0.0.2, L3 dst 10.0.0.1) Port 6 VLAN 31 (1 hosts total) from remote DP t2-sw1 port Port 7
Sep 23 01:53:27 faucet.valve INFO     DPID 115621677691 (0x1aeb96ca7b) t1-sw2 L2 learned a0:36:9f:01:de:1d (L2 type 0x0800, L2 dst a0:36:9f:01:de:1c, L3 src 10.0.0.2, L3 dst 10.0.0.1) Port 6 VLAN 31 (1 hosts total) from remote DP t2-sw1 port Port 7
Sep 23 01:53:28 faucet.valve INFO     DPID 115621677691 (0x1aeb96ca7b) t1-sw2 L2 learned a0:36:9f:01:de:1d (L2 type 0x0800, L2 dst a0:36:9f:01:de:1c, L3 src 10.0.0.2, L3 dst 10.0.0.1) Port 6 VLAN 31 (1 hosts total) from remote DP t2-sw1 port Port 7
Sep 23 01:53:29 faucet.valve INFO     DPID 115621677691 (0x1aeb96ca7b) t1-sw2 L2 learned a0:36:9f:01:de:1d (L2 type 0x0800, L2 dst a0:36:9f:01:de:1c, L3 src 10.0.0.2, L3 dst 10.0.0.1) Port 6 VLAN 31 (1 hosts total) from remote DP t2-sw1 port Port 7
Sep 23 01:53:30 faucet.valve INFO     DPID 115621677691 (0x1aeb96ca7b) t1-sw2 L2 learned a0:36:9f:01:de:1d (L2 type 0x0800, L2 dst a0:36:9f:01:de:1c, L3 src 10.0.0.2, L3 dst 10.0.0.1) Port 6 VLAN 31 (1 hosts total) from remote DP t2-sw1 port Port 7
Sep 23 01:53:32 faucet.valve INFO     DPID 115621677691 (0x1aeb96ca7b) t1-sw2 L2 learned a0:36:9f:01:de:1d (L2 type 0x0800, L2 dst a0:36:9f:01:de:1c, L3 src 10.0.0.2, L3 dst 10.0.0.1) Port 6 VLAN 31 (1 hosts total) from remote DP t2-sw1 port Port 7
Sep 23 01:53:33 faucet.valve INFO     DPID 115621677691 (0x1aeb96ca7b) t1-sw2 L2 learned a0:36:9f:01:de:1d (L2 type 0x0800, L2 dst a0:36:9f:01:de:1c, L3 src 10.0.0.2, L3 dst 10.0.0.1) Port 6 VLAN 31 (1 hosts total) from remote DP t2-sw1 port Port 7
Sep 23 01:53:34 faucet.valve INFO     DPID 115621677691 (0x1aeb96ca7b) t1-sw2 L2 learned a0:36:9f:01:de:1d (L2 type 0x0800, L2 dst a0:36:9f:01:de:1c, L3 src 10.0.0.2, L3 dst 10.0.0.1) Port 6 VLAN 31 (1 hosts total) from remote DP t2-sw1 port Port 7
Sep 23 01:53:35 faucet.valve INFO     DPID 115621677691 (0x1aeb96ca7b) t1-sw2 L2 learned a0:36:9f:01:de:1d (L2 type 0x0800, L2 dst a0:36:9f:01:de:1c, L3 src 10.0.0.2, L3 dst 10.0.0.1) Port 6 VLAN 31 (1 hosts total) from remote DP t2-sw1 port Port 7
Sep 23 01:53:36 faucet.valve INFO     DPID 115621677691 (0x1aeb96ca7b) t1-sw2 L2 learned a0:36:9f:01:de:1d (L2 type 0x0800, L2 dst a0:36:9f:01:de:1c, L3 src 10.0.0.2, L3 dst 10.0.0.1) Port 6 VLAN 31 (1 hosts total) from remote DP t2-sw1 port Port 7
Sep 23 01:53:37 faucet.valve INFO     DPID 115621677691 (0x1aeb96ca7b) t1-sw2 L2 learned a0:36:9f:01:de:1d (L2 type 0x0800, L2 dst a0:36:9f:01:de:1c, L3 src 10.0.0.2, L3 dst 10.0.0.1) Port 6 VLAN 31 (1 hosts total) from remote DP t2-sw1 port Port 7
Sep 23 01:53:38 faucet.valve INFO     DPID 115621677691 (0x1aeb96ca7b) t1-sw2 L2 learned a0:36:9f:01:de:1d (L2 type 0x0800, L2 dst a0:36:9f:01:de:1c, L3 src 10.0.0.2, L3 dst 10.0.0.1) Port 6 VLAN 31 (1 hosts total) from remote DP t2-sw1 port Port 7
Sep 23 01:53:39 faucet.valve INFO     DPID 115621677691 (0x1aeb96ca7b) t1-sw2 L2 learned a0:36:9f:01:de:1d (L2 type 0x0800, L2 dst a0:36:9f:01:de:1c, L3 src 10.0.0.2, L3 dst 10.0.0.1) Port 6 VLAN 31 (1 hosts total) from remote DP t2-sw1 port Port 7
Sep 23 01:53:40 faucet.valve INFO     DPID 115621677691 (0x1aeb96ca7b) t1-sw2 L2 learned a0:36:9f:01:de:1d (L2 type 0x0800, L2 dst a0:36:9f:01:de:1c, L3 src 10.0.0.2, L3 dst 10.0.0.1) Port 6 VLAN 31 (1 hosts total) from remote DP t2-sw1 port Port 7
Sep 23 01:53:41 faucet.valve INFO     DPID 115621677691 (0x1aeb96ca7b) t1-sw2 L2 learned a0:36:9f:01:de:1d (L2 type 0x0800, L2 dst a0:36:9f:01:de:1c, L3 src 10.0.0.2, L3 dst 10.0.0.1) Port 6 VLAN 31 (1 hosts total) from remote DP t2-sw1 port Port 7
Sep 23 01:53:42 faucet.valve INFO     DPID 115621677691 (0x1aeb96ca7b) t1-sw2 L2 learned a0:36:9f:01:de:1d (L2 type 0x0800, L2 dst a0:36:9f:01:de:1c, L3 src 10.0.0.2, L3 dst 10.0.0.1) Port 6 VLAN 31 (1 hosts total) from remote DP t2-sw1 port Port 7
Sep 23 01:53:43 faucet.valve INFO     DPID 115621677691 (0x1aeb96ca7b) t1-sw2 L2 learned a0:36:9f:01:de:1d (L2 type 0x0800, L2 dst a0:36:9f:01:de:1c, L3 src 10.0.0.2, L3 dst 10.0.0.1) Port 6 VLAN 31 (1 hosts total) from remote DP t2-sw1 port Port 7
Sep 23 01:53:44 faucet.valve INFO     DPID 115621677691 (0x1aeb96ca7b) t1-sw2 L2 learned a0:36:9f:01:de:1d (L2 type 0x0800, L2 dst a0:36:9f:01:de:1c, L3 src 10.0.0.2, L3 dst 10.0.0.1) Port 6 VLAN 31 (1 hosts total) from remote DP t2-sw1 port Port 7
Sep 23 01:53:45 faucet.valve INFO     DPID 115621677691 (0x1aeb96ca7b) t1-sw2 L2 learned a0:36:9f:01:de:1d (L2 type 0x0806, L2 dst a0:36:9f:01:de:1c, L3 src 10.0.0.2, L3 dst 10.0.0.1) Port 6 VLAN 31 (1 hosts total) from remote DP t2-sw1 port Port 7
Sep 23 01:53:45 faucet.valve INFO     DPID 115621677691 (0x1aeb96ca7b) t1-sw2 L2 learned a0:36:9f:01:de:1d (L2 type 0x0800, L2 dst a0:36:9f:01:de:1c, L3 src 10.0.0.2, L3 dst 10.0.0.1) Port 6 VLAN 31 (1 hosts total) from remote DP t2-sw1 port Port 7
Sep 23 01:53:46 faucet.valve INFO     DPID 115621677691 (0x1aeb96ca7b) t1-sw2 L2 learned a0:36:9f:01:de:1d (L2 type 0x0806, L2 dst a0:36:9f:01:de:1c, L3 src 10.0.0.2, L3 dst 10.0.0.1) Port 6 VLAN 31 (1 hosts total) from remote DP t2-sw1 port Port 7
Sep 23 01:53:46 faucet.valve INFO     DPID 115621677691 (0x1aeb96ca7b) t1-sw2 L2 learned a0:36:9f:01:de:1d (L2 type 0x0800, L2 dst a0:36:9f:01:de:1c, L3 src 10.0.0.2, L3 dst 10.0.0.1) Port 6 VLAN 31 (1 hosts total) from remote DP t2-sw1 port Port 7
Sep 23 01:53:47 faucet.valve INFO     DPID 115621677691 (0x1aeb96ca7b) t1-sw2 L2 learned a0:36:9f:01:de:1d (L2 type 0x0806, L2 dst a0:36:9f:01:de:1c, L3 src 10.0.0.2, L3 dst 10.0.0.1) Port 6 VLAN 31 (1 hosts total) from remote DP t2-sw1 port Port 7
```

**Comment by grafnu** [comment] 2019-09-27 15:27
I was running into something similar, but it wasn't "unicast wouldn't learn" but rather that broadcast wouldn't learn.  The topology started with:
```
 >A--B
  |\/|
  |/\|
  C  D
```
Which triggers the NoReflection flood manager with A as the root node.  After link down, the topology is:
```
 >A--B
  | /|
  |/ |
  C  D
```
D finds a flooding path to C, but because of the algorithm B is not allowed to broadcast to D so there is no path from C to D.

**Comment by anarkiwi** [comment] 2019-09-30 21:02
That would be a separate issue - the no reflection model currently requires a star topology.

This issue is caused by rings not being handled correctly (there are a couple of causes, including networkx returning different shortest paths of equal length - which FAUCET did not expect and needs  to handle).

**Comment by anarkiwi** [comment] 2019-10-01 00:01
Fixed by https://github.com/faucetsdn/faucet/pull/3262.

**Closed by anarkiwi** 2019-10-01 00:01 UTC
Labels: bug
