### ISSUE TITLE
OVS tutorial for Faucet 1.8.3 and later doesn't work

### ISSUE THREAD

**Issue by joestringer** [faucetsdn/faucet#2276] opened 2018-08-13 09:44 UTC
Reported on ovs-bugs:

https://mail.openvswitch.org/pipermail/ovs-discuss/2018-August/047180.html

<html><head></head><body><div style="font-family: Verdana;font-size: 12.0px;"><div>Hey all!</div>

<div>&nbsp;</div>

<div>I just tried the OVS Faucet tutorial http://docs.openvswitch.org/en/latest/tutorials/faucet/ but since Faucet 1.8.3 this does not work anymore.<br/>
>From https://github.com/faucetsdn/faucet/releases/tag/1.8.3 :</div>

<div>* Only provision flows for ports that are known to be up (fixes stacking when redundant links are down on initialization, among other cases)</div>

<div>which makes it that most of the rules discussed in the tutorial won&#39;t be created. The tutorial works with 1.8.2.</div>

<div>&nbsp;</div>

<div>Also, the Dockerfile was renamed so</div>

<div>&nbsp; docker build -t faucet/faucet .</div>

<div>should be</div>

<div>&nbsp; docker build -t faucet/faucet -f Dockerfile.faucet .</div>

<div>&nbsp;</div>

<div>Greetings,</div>

<div>Matthias Ableidinger</div></div></body></html>

**Comment by gizmoguy** [comment] 2018-08-19 09:56
Thanks for passing on @joestringer, as correctly pointed out by the user faucet has an added optimisation to not configure ports which are not up (we require less flowmods this way).

The reason the ports don't come up in this case is that the OVS sandbox uses netdev_dummy which bypasses the linux networking stack and uses a dummy one. I've checked out the code and it is possible to force the ports to come up by issuing a command:

`ovs-appctl netdev-dummy/set-admin-state up`

This will trigger faucet to push some flowmods for p1-p5. However looks like there are still issues when running the ofproto/trace -generate commands. I am not seeing any packets being punted to faucet (have enabled ofchannel_log in faucet and don't even see a packet_in being sent towards faucet). Currently testing with OVS 2.9.2.

Will attempt to spend some more time later it the week to track down why packet_ins aren't being generated.

**Comment by gizmoguy** [comment] 2018-08-21 23:09
I've discovered the cause of the -generate flag not working for controller flows, and it's this bug here:

https://github.com/openvswitch/ovs-issues/issues/145

Have updated ovs-discuss mailing list to see if we can come to a decision on how to fix properly.

**Comment by gizmoguy** [comment] 2018-08-24 23:11
Ben has written some patches against ovs@master which fix the bugs that make the tutorial work again:

https://patchwork.ozlabs.org/project/openvswitch/list/?series=62396
https://patchwork.ozlabs.org/patch/962002/ 

Until these are merged and released I will update the ovs faucet tutorial to recommend using either ovs@master or ovs <= 2.8 for the tutorial.

**Comment by gizmoguy** [comment] 2018-09-12 00:48
Patch submitted upstream to update the faucet ovs tutorial:

https://mail.openvswitch.org/pipermail/ovs-dev/2018-September/352046.html

**Comment by anarkiwi** [comment] 2019-07-28 19:28
Status update - looks like the patch is not yet applied (from http://docs.openvswitch.org/en/latest/tutorials/faucet/).

**Comment by gizmoguy** [comment] 2019-07-28 22:49
Bumped: https://mail.openvswitch.org/pipermail/ovs-dev/2019-July/361104.html

**Comment by anarkiwi** [comment] 2020-03-02 20:26
Looks like no activity on that thread?

**Comment by gizmoguy** [comment] 2020-03-03 02:23
Ben has now been bumped in person, he apologizes profusely :)

**Comment by anarkiwi** [comment] 2020-07-12 21:20
status update - as of 13/7/20 looks like not yet commited (https://github.com/openvswitch/ovs/commits/master/Documentation/tutorials/faucet.rst).

**Comment by gizmoguy** [comment] 2021-01-10 20:42
My patch has now been merged upstream.

**Closed by gizmoguy** 2021-01-10 20:42 UTC
Labels: bug
