### ISSUE TITLE
Bug in mirroring multiple ports in a single configuration change stops communication between ports

### ISSUE THREAD

**Issue by cglewis** [faucetsdn/faucet#2151] opened 2018-07-08 15:24 UTC
Steps to reproduce, start with a faucet.yaml such as:
```
dps:
  switch-1:
    dp_id: 1
    hardware: Open vSwitch
    interfaces:
      1:
        native_vlan: 8
      2:
        native_vlan: 8
      3:
        description: mirror
        output_only: true
vlans:
  8:
```

Ensure you've started Faucet with `FAUCET_CONFIG_STAT_RELOAD=1`.

Change your faucet.yaml to:
```
dps:
  switch-1:
    dp_id: 1
    hardware: Open vSwitch
    interfaces:
      1:
        native_vlan: 8
      2:
        native_vlan: 8
      3:
        description: mirror
        mirror:
        - 1
        - 2
        output_only: true
vlans:
  8:
```

Communication between h1 and h2 will stop working, at least on a warm start.  It seems if the config was already set to multiple mirror ports prior to Faucet starting, it's ok, or if the mirror ports get added iteratively.  It seems to only cause issues when they are added in bulk for a single configuration change on a warm start, as near as I can tell.

**Comment by anarkiwi** [comment] 2018-07-09 09:48
I have not yet been able to duplicate the problem.

I am attempting to do so with the following test:

https://github.com/faucetsdn/faucet/blob/master/tests/integration/mininet_tests.py#L3794

Does this test pass for you, with your switch?

**Comment by cglewis** [comment] 2018-07-09 16:48
So I ran that test and it passes. I'm not sure if this is related, but I tried changing the `restart=True` to `restart=False` and the test fails for me.

I tried starting Faucet using docker-compose without `FAUCET_CONFIG_STAT_RELOAD` set and instead triggered configuration updates in 2 different ways, which each behaved differently.

If I did:

```
docker exec -it faucet_faucet_1 pkill -HUP -f faucet.faucet
```
The logs would so the change pick up (as a Cold start) and traffic would stop between the two hosts when mirror ports were added to the config.

On the other hand, if I instead did:
```
docker restart faucet_faucet_1
```
Then traffic would continue to communicate with the added mirror ports.

**Comment by anarkiwi** [comment] 2018-07-09 20:49
This is very strange. What is the switch in use, and is it possible to get
a flow dump from the switch when the problem occurs?

**Comment by cglewis** [comment] 2018-07-09 20:51
I'm just using Mininet 2.2.1 with Open vSwitch on Ubuntu 16.04.4 with Docker 18.03.1-ce

**Comment by anarkiwi** [comment] 2018-07-09 20:52
Restart=True in the change call just causes a HUP (if you don't call with
that then the config is changed without signaling FAUCET, so FAUCET does
nothing and the mirror is not applied).

**Comment by cglewis** [comment] 2018-07-09 20:53
Ah, gotcha.  I wasn't sure since there was also a HUP arg.

**Comment by anarkiwi** [comment] 2018-07-09 21:22
Ah, OK OVS - very good. We use mininet 2.2.2 mostly but that should not
make a difference.

Can we get the flow table dump from OVS? There must be some subtle order of
operations thing here, that will helping me understand from the bad flow
table what happened.

This one is a good one! :)

**Comment by cglewis** [comment] 2018-07-09 21:31
Sure, what's the most useful way to get that and at what point(s) in the operations?

**Comment by anarkiwi** [comment] 2018-07-09 22:01
It looks like you have a 100% failed state once the problem occurs so
that's good.

May I have dump-flows from before, and then after applying the breaking
config?

Also what OVS do you have? I am on 2.9.2. I doubt it makes a difference but
I'll test with that as well to make sure I get the same as you.

**Comment by cglewis** [comment] 2018-07-09 23:16
Here's the flows before mirroring, h1 and h2 can ping each other:
```
$ sudo ovs-ofctl dump-flows s1
NXST_FLOW reply (xid=0x4):
 cookie=0x5adc15c0, duration=29.178s, table=0, n_packets=18, n_bytes=1524, idle_age=2, priority=9099,in_port=1 actions=resubmit(,1)
 cookie=0x5adc15c0, duration=29.178s, table=0, n_packets=18, n_bytes=1524, idle_age=1, priority=9099,in_port=2 actions=resubmit(,1)
 cookie=0x5adc15c0, duration=29.180s, table=0, n_packets=8, n_bytes=656, idle_age=3, priority=0 actions=drop
 cookie=0x5adc15c0, duration=29.178s, table=1, n_packets=0, n_bytes=0, idle_age=29, priority=9099,in_port=3 actions=drop
 cookie=0x5adc15c0, duration=29.178s, table=1, n_packets=18, n_bytes=1524, idle_age=2, priority=9000,in_port=1,vlan_tci=0x0000/0x1fff actions=mod_vlan_vid:8,resubmit(,3)
 cookie=0x5adc15c0, duration=29.178s, table=1, n_packets=18, n_bytes=1524, idle_age=1, priority=9000,in_port=2,vlan_tci=0x0000/0x1fff actions=mod_vlan_vid:8,resubmit(,3)
 cookie=0x5adc15c0, duration=29.180s, table=1, n_packets=0, n_bytes=0, idle_age=29, priority=0 actions=drop
 cookie=0x5adc15c0, duration=29.180s, table=2, n_packets=0, n_bytes=0, idle_age=29, priority=0 actions=drop
 cookie=0x5adc15c0, duration=29.180s, table=3, n_packets=0, n_bytes=0, idle_age=29, priority=9099,dl_src=ff:ff:ff:ff:ff:ff actions=drop
 cookie=0x5adc15c0, duration=29.180s, table=3, n_packets=0, n_bytes=0, idle_age=29, priority=9001,dl_src=0e:00:00:00:00:01 actions=drop
 cookie=0x5adc15c0, duration=28.735s, table=3, n_packets=17, n_bytes=1438, hard_timeout=295, idle_age=2, priority=9098,in_port=1,dl_vlan=8,dl_src=00:00:00:00:00:01 actions=resubmit(,7)
 cookie=0x5adc15c0, duration=28.707s, table=3, n_packets=17, n_bytes=1438, hard_timeout=302, idle_age=1, priority=9098,in_port=2,dl_vlan=8,dl_src=00:00:00:00:00:02 actions=resubmit(,7)
 cookie=0x5adc15c0, duration=29.178s, table=3, n_packets=2, n_bytes=172, idle_age=28, priority=9000,dl_vlan=8 actions=CONTROLLER:96,resubmit(,7)
 cookie=0x5adc15c0, duration=29.179s, table=3, n_packets=0, n_bytes=0, idle_age=29, priority=0 actions=resubmit(,7)
 cookie=0x5adc15c0, duration=28.734s, table=7, n_packets=10, n_bytes=868, idle_timeout=295, idle_age=2, priority=9099,dl_vlan=8,dl_dst=00:00:00:00:00:01 actions=strip_vlan,output:1
 cookie=0x5adc15c0, duration=28.707s, table=7, n_packets=9, n_bytes=826, idle_timeout=302, idle_age=2, priority=9099,dl_vlan=8,dl_dst=00:00:00:00:00:02 actions=strip_vlan,output:2
 cookie=0x5adc15c0, duration=29.180s, table=7, n_packets=0, n_bytes=0, idle_age=29, priority=0 actions=drop
 cookie=0x5adc15c0, duration=29.180s, table=7, n_packets=17, n_bytes=1354, idle_age=1, priority=9000 actions=resubmit(,8)
 cookie=0x5adc15c0, duration=29.180s, table=8, n_packets=0, n_bytes=0, idle_age=29, priority=9099,dl_dst=01:00:0c:cc:cc:cd actions=drop
 cookie=0x5adc15c0, duration=29.180s, table=8, n_packets=0, n_bytes=0, idle_age=29, priority=9099,dl_dst=01:80:c2:00:00:00/ff:ff:ff:ff:ff:f0 actions=drop
 cookie=0x5adc15c0, duration=29.178s, table=8, n_packets=1, n_bytes=42, idle_age=8, priority=9004,dl_vlan=8,dl_dst=ff:ff:ff:ff:ff:ff actions=strip_vlan,output:1,output:2
 cookie=0x5adc15c0, duration=29.178s, table=8, n_packets=16, n_bytes=1312, idle_age=1, priority=9003,dl_vlan=8,dl_dst=33:33:00:00:00:00/ff:ff:00:00:00:00 actions=strip_vlan,output:1,output:2
 cookie=0x5adc15c0, duration=29.179s, table=8, n_packets=0, n_bytes=0, idle_age=29, priority=9001,dl_vlan=8,dl_dst=01:80:c2:00:00:00/ff:ff:ff:00:00:00 actions=strip_vlan,output:1,output:2
 cookie=0x5adc15c0, duration=29.179s, table=8, n_packets=0, n_bytes=0, idle_age=29, priority=9002,dl_vlan=8,dl_dst=01:00:5e:00:00:00/ff:ff:ff:00:00:00 actions=strip_vlan,output:1,output:2
 cookie=0x5adc15c0, duration=29.179s, table=8, n_packets=0, n_bytes=0, idle_age=29, priority=9000,dl_vlan=8 actions=strip_vlan,output:1,output:2
 cookie=0x5adc15c0, duration=29.180s, table=8, n_packets=0, n_bytes=0, idle_age=29, priority=0 actions=drop
```

Here's adding the mirror ports and h1 and h2 can no longer ping each other once the configuration change is loaded:
```
$ sudo ovs-ofctl dump-flows s1
NXST_FLOW reply (xid=0x4):
 cookie=0x5adc15c0, duration=7.794s, table=0, n_packets=8, n_bytes=784, idle_age=0, priority=9099,in_port=1 actions=resubmit(,1)
 cookie=0x5adc15c0, duration=7.794s, table=0, n_packets=7, n_bytes=686, idle_age=0, priority=9099,in_port=2 actions=resubmit(,1)
 cookie=0x5adc15c0, duration=7.797s, table=0, n_packets=2, n_bytes=196, idle_age=7, priority=0 actions=drop
 cookie=0x5adc15c0, duration=7.794s, table=1, n_packets=0, n_bytes=0, idle_age=7, priority=9099,in_port=3 actions=drop
 cookie=0x5adc15c0, duration=7.794s, table=1, n_packets=8, n_bytes=784, idle_age=0, priority=9000,in_port=1,vlan_tci=0x0000/0x1fff actions=output:3,mod_vlan_vid:8,resubmit(,3)
 cookie=0x5adc15c0, duration=7.794s, table=1, n_packets=7, n_bytes=686, idle_age=0, priority=9000,in_port=2,vlan_tci=0x0000/0x1fff actions=output:3,mod_vlan_vid:8,resubmit(,3)
 cookie=0x5adc15c0, duration=7.797s, table=1, n_packets=0, n_bytes=0, idle_age=7, priority=0 actions=drop
 cookie=0x5adc15c0, duration=7.797s, table=2, n_packets=0, n_bytes=0, idle_age=7, priority=0 actions=drop
 cookie=0x5adc15c0, duration=7.797s, table=3, n_packets=0, n_bytes=0, idle_age=7, priority=9099,dl_src=ff:ff:ff:ff:ff:ff actions=drop
 cookie=0x5adc15c0, duration=7.797s, table=3, n_packets=0, n_bytes=0, idle_age=7, priority=9001,dl_src=0e:00:00:00:00:01 actions=drop
 cookie=0x5adc15c0, duration=6.935s, table=3, n_packets=7, n_bytes=686, hard_timeout=295, idle_age=0, priority=9098,in_port=2,dl_vlan=8,dl_src=00:00:00:00:00:02 actions=resubmit(,7)
 cookie=0x5adc15c0, duration=6.935s, table=3, n_packets=8, n_bytes=784, hard_timeout=299, idle_age=0, priority=9098,in_port=1,dl_vlan=8,dl_src=00:00:00:00:00:01 actions=resubmit(,7)
 cookie=0x5adc15c0, duration=7.794s, table=3, n_packets=0, n_bytes=0, idle_age=7, priority=9000,dl_vlan=8 actions=CONTROLLER:96,resubmit(,7)
 cookie=0x5adc15c0, duration=7.797s, table=3, n_packets=0, n_bytes=0, idle_age=7, priority=0 actions=resubmit(,7)
 cookie=0x5adc15c0, duration=6.935s, table=7, n_packets=8, n_bytes=784, idle_timeout=295, idle_age=0, priority=9099,dl_vlan=8,dl_dst=00:00:00:00:00:02 actions=output:3,output:2
 cookie=0x5adc15c0, duration=6.935s, table=7, n_packets=7, n_bytes=686, idle_timeout=299, idle_age=0, priority=9099,dl_vlan=8,dl_dst=00:00:00:00:00:01 actions=output:3,output:1
 cookie=0x5adc15c0, duration=7.797s, table=7, n_packets=0, n_bytes=0, idle_age=7, priority=0 actions=drop
 cookie=0x5adc15c0, duration=7.797s, table=7, n_packets=0, n_bytes=0, idle_age=7, priority=9000 actions=resubmit(,8)
 cookie=0x5adc15c0, duration=7.797s, table=8, n_packets=0, n_bytes=0, idle_age=7, priority=9099,dl_dst=01:00:0c:cc:cc:cd actions=drop
 cookie=0x5adc15c0, duration=7.797s, table=8, n_packets=0, n_bytes=0, idle_age=7, priority=9099,dl_dst=01:80:c2:00:00:00/ff:ff:ff:ff:ff:f0 actions=drop
 cookie=0x5adc15c0, duration=7.794s, table=8, n_packets=0, n_bytes=0, idle_age=7, priority=9004,dl_vlan=8,dl_dst=ff:ff:ff:ff:ff:ff actions=strip_vlan,output:1,output:2
 cookie=0x5adc15c0, duration=7.794s, table=8, n_packets=0, n_bytes=0, idle_age=7, priority=9003,dl_vlan=8,dl_dst=33:33:00:00:00:00/ff:ff:00:00:00:00 actions=strip_vlan,output:1,output:2
 cookie=0x5adc15c0, duration=7.794s, table=8, n_packets=0, n_bytes=0, idle_age=7, priority=9001,dl_vlan=8,dl_dst=01:80:c2:00:00:00/ff:ff:ff:00:00:00 actions=strip_vlan,output:1,output:2
 cookie=0x5adc15c0, duration=7.794s, table=8, n_packets=0, n_bytes=0, idle_age=7, priority=9002,dl_vlan=8,dl_dst=01:00:5e:00:00:00/ff:ff:ff:00:00:00 actions=strip_vlan,output:1,output:2
 cookie=0x5adc15c0, duration=7.794s, table=8, n_packets=0, n_bytes=0, idle_age=7, priority=9000,dl_vlan=8 actions=strip_vlan,output:1,output:2
 cookie=0x5adc15c0, duration=7.797s, table=8, n_packets=0, n_bytes=0, idle_age=7, priority=0 actions=drop
```

OVS Version:
```
$ sudo ovs-ofctl --version
ovs-ofctl (Open vSwitch) 2.5.4
Compiled Oct 30 2017 10:38:01
OpenFlow versions 0x1:0x4
```

**Comment by anarkiwi** [comment] 2018-07-10 02:50
OK thanks - that's helpful. It looks like the strip_vlan action is going
missing on output. That will definitely break it.

One more test if you are able? Would you be able to upgrade OVS? If that's
painful then would you be able to snoop the OF connection (a pcap is fine),
I want to see whether FAUCET sent the bad flow. I'm still unable to
reproduce locally, so that will add another puzzle piece.

In the meantime, I'll assume FAUCET is sending the wrong flow and speculate
as to why, but a OF trace showing it did would be conclusive.


--- before-short.txt    2018-07-10 14:44:38.017454343 +1200
+++ after-short.txt     2018-07-10 14:45:15.049706600 +1200
@@ -2,18 +2,18 @@
 table=0 priority=9099,in_port=2 actions=resubmit(,1)
 table=0 priority=0 actions=drop
 table=1 priority=9099,in_port=3 actions=drop
-table=1 priority=9000,in_port=1,vlan_tci=0x0000/0x1fff
actions=mod_vlan_vid:8,resubmit(,3)
-table=1 priority=9000,in_port=2,vlan_tci=0x0000/0x1fff
actions=mod_vlan_vid:8,resubmit(,3)
+table=1 priority=9000,in_port=1,vlan_tci=0x0000/0x1fff
actions=output:3,mod_vlan_vid:8,resubmit(,3)
+table=1 priority=9000,in_port=2,vlan_tci=0x0000/0x1fff
actions=output:3,mod_vlan_vid:8,resubmit(,3)
 table=1 priority=0 actions=drop
 table=2 priority=0 actions=drop
 table=3 priority=9099,dl_src=ff:ff:ff:ff:ff:ff actions=drop
 table=3 priority=9001,dl_src=0e:00:00:00:00:01 actions=drop
-table=3 priority=9098,in_port=1,dl_vlan=8,dl_src=00:00:00:00:00:01
actions=resubmit(,7)
 table=3 priority=9098,in_port=2,dl_vlan=8,dl_src=00:00:00:00:00:02
actions=resubmit(,7)
+table=3 priority=9098,in_port=1,dl_vlan=8,dl_src=00:00:00:00:00:01
actions=resubmit(,7)
 table=3 priority=9000,dl_vlan=8 actions=CONTROLLER:96,resubmit(,7)
 table=3 priority=0 actions=resubmit(,7)
-table=7 priority=9099,dl_vlan=8,dl_dst=00:00:00:00:00:01
actions=strip_vlan,output:1
-table=7 priority=9099,dl_vlan=8,dl_dst=00:00:00:00:00:02
actions=strip_vlan,output:2
*+table=7 priority=9099,dl_vlan=8,dl_dst=00:00:00:00:00:02
actions=output:3,output:2*
*+table=7 priority=9099,dl_vlan=8,dl_dst=00:00:00:00:00:01
actions=output:3,output:1*
 table=7 priority=0 actions=drop
 table=7 priority=9000 actions=resubmit(,8)
 table=8 priority=9099,dl_dst=01:00:0c:cc:cc:cd actions=drop

**Comment by anarkiwi** [comment] 2018-07-10 03:29
I did find a problem where floods are multiply output to the mirror port:

 cookie=0xbf757d78be1bd725, duration=4.799s, table=8, n_packets=4,
n_bytes=336, priority=9000,dl_vlan=100 actions=*output:4,output:4,*pop_
vlan,output:1,output:2,output:3

I am fixing that now. I don't know what OVS 2.5 would do with that.

Please try with master now and see if that makes a difference?

Also you can add -OOpenFlow13 to the dump command (so we use the same
dump-flows format, new style).

**Comment by cglewis** [comment] 2018-07-10 03:55
Ok, I updated OVS to 2.9.90 (latest from master), though mininet is still 2.2.1.  I also pulled in your latest merge, and still getting the same behavior.  I'm working on building a fresh Ubuntu 16.04 VM to ensure there's not something goofy with my box specifically, since you can't reproduce.  I'll let you know how that goes.

**Comment by cglewis** [comment] 2018-07-10 15:13
Ok, I setup a completely brand new VM and loaded up Ubuntu 16.04.4 on it, straight from the ISO.  I did:
```
sudo apt-get update && sudo apt-get upgrade
```

Installed Docker and docker-compose, versions are: 18.03.1-ce and 1.12.2 respectively.

Then I installed mininet with `sudo apt-get install mininet`
Which installed 2.2.1 and OVS 2.5.4.

Restarted the VM for good measure.

I pulled down Faucet from master (as of this morning) and started it with:
```
docker-compose -f docker-compose.yaml up --build -d
```

I then put this in my /etc/faucet/faucet.yaml:
```
dps:
  switch-1:
    dp_id: 1
    hardware: Open vSwitch
    interfaces:
      1:
        native_vlan: 8
      2:
        native_vlan: 8
      3:
        description: mirror
        output_only: true
vlans:
  8:
```

Sent HUP to have Faucet pick up the config:
```
docker exec -it faucet_faucet_1 pkill -HUP -f faucet.faucet
```

Started mininet:
```
sudo mn --topo single,3 --mac --switch ovsk --controller=remote,ip=127.0.0.1:6653
```

Started a ping (which worked):
```
h1 ping h2
```

Changed my /etc/faucet/faucet.yaml to:
```
dps:
  switch-1:
    dp_id: 1
    hardware: Open vSwitch
    interfaces:
      1:
        native_vlan: 8
      2:
        native_vlan: 8
      3:
        description: mirror
        mirror:
        - 1
        - 2
        output_only: true
vlans:
  8:
```

Sent HUP:
```
docker exec -it faucet_faucet_1 pkill -HUP -f faucet faucet
```

Pings between h1 and h2 stopped working.

I realize that OVS is a pretty old version, but that's still the latest available package on Ubuntu 16.04 which is still LTS and has another 3 years of life.

Though, updated to the latest OVS last night didn't seem to make a difference me.

Are you able to replicate?

**Comment by anarkiwi** [comment] 2018-07-10 20:33
Thanks. I'm sorry for the trouble. I am not yet able to replicate the
problem. Would you be able to send me a pcap of the OF connection, from
your setup?

**Comment by anarkiwi** [comment] 2018-07-11 08:40
OK, the trace confirms that FAUCET is definitely sending the wrong flow (missing strip_vlan).

Still don't know why but that of course eliminates OVS.

Looking further.

OpenFlow 1.3
    Version: 1.3 (0x04)
    Type: OFPT_FLOW_MOD (14)
    Length: 112
    Transaction ID: 1559546886
    Cookie: 0x000000005adc15c0
    Cookie mask: 0x0000000000000000
    Table ID: 7
    Command: OFPFC_ADD (0)
    Idle timeout: 300
    Hard timeout: 0
    Priority: 9099
    Buffer ID: OFP_NO_BUFFER (0xffffffff)
    Out port: 0
    Out group: 0
    Flags: 0x0000
        .... .... .... ...0 = Send flow removed: False
        .... .... .... ..0. = Check overlap: False
        .... .... .... .0.. = Reset counts: False
        .... .... .... 0... = Don't count packets: False
        .... .... ...0 .... = Don't count bytes: False
    Pad: 0000
    Match
        Type: OFPMT_OXM (1)
        Length: 20
        OXM field
            Class: OFPXMC_OPENFLOW_BASIC (0x8000)
            0000 011. = Field: OFPXMT_OFB_ETH_DST (3)
            .... ...0 = Has mask: False
            Length: 6
            Value: 00:00:00_00:00:02 (00:00:00:00:00:02)
        OXM field
            Class: OFPXMC_OPENFLOW_BASIC (0x8000)
            0000 110. = Field: OFPXMT_OFB_VLAN_VID (6)
            .... ...0 = Has mask: False
            Length: 2
            ...1 .... .... .... = OFPVID_PRESENT: True
            .... 0000 0000 1000 = Value: 8
        Pad: 00000000
    Instruction
        Type: OFPIT_APPLY_ACTIONS (4)
        Length: 40
        Pad: 00000000
        Action
            Type: OFPAT_OUTPUT (0)
            Length: 16
            Port: 3
            Max length: 0
            Pad: 000000000000
        Action
            Type: OFPAT_OUTPUT (0)
            Length: 16
            Port: 2
            Max length: 0
            Pad: 000000000000

**Comment by anarkiwi** [comment] 2018-07-11 11:14
Fixed by https://github.com/faucetsdn/faucet/pull/2155

**Closed by anarkiwi** 2018-07-11 11:14 UTC
Labels: bug

**Comment by cglewis** [comment] 2018-07-11 13:59
Can confirm that fixed it, thanks!
